Repository ng-select/ng-select, pull requests merged in 2024-09, with the labels that each got.

#2445 fix: marks fixed placeholder as default
  .github/workflows/auto-approve.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependabot.yml
  .github/workflows/release.yml
  package.json
  src/demo/app/examples/fixed-placeholder-example/fixed-placeholder-example.component.html
  src/demo/app/examples/fixed-placeholder-example/fixed-placeholder-example.component.ts
  src/demo/app/routes.ts
  src/ng-option-highlight/lib/ng-option-highlight.directive.spec.ts
  src/ng-option-highlight/lib/ng-option-highlight.directive.ts
  src/ng-select/lib/ng-dropdown-panel.component.ts
  src/ng-select/lib/ng-option.component.ts
  src/ng-select/lib/ng-select.component.html
  src/ng-select/lib/ng-select.component.spec.ts
  src/ng-select/lib/ng-select.component.ts
  src/ng-select/lib/ng-select.module.ts
  src/ng-select/lib/ng-templates.directive.ts
Labels: bug

#2450 fix: fixes release issue
  package.json
Labels: bug

#2457 fix: "Clear all" span aria role
  src/ng-select/lib/ng-select.component.html
Labels: bug, dependencies

#2459 feat: adds `aria-label` for input
  src/ng-select/lib/ng-select.component.html
  src/ng-select/lib/ng-select.component.spec.ts
  src/ng-select/lib/ng-select.component.ts
Labels: new feature
